[terminal]
shell = "sptlrx"
[font]
size=20
offset = { y = -20, x = -5 }

[font.normal]
family = "FOT-Slump Std"
style = "Regular"


[window]
class = { general = "lyrics" }
[window.position]
x = 580 
y = 12
[window.dimensions]
columns = 133
lines = 40